services:
  api:
    build: ./api
    container_name: wse_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - api_data:/data
      - ./uploads:/app/uploads
    restart: unless-stopped


  web:
    build: ./web
    container_name: wse_web
    environment:
      - VITE_PUBLIC_API_BASE=http://localhost:8000
      - VITE_APP_TITLE=White Safe Estate
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: wse_bot
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped

volumes:
  api_data:
